# Generated by Django 2.1.3 on 2018-12-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='max_stored_runs',
            field=models.IntegerField(default=1),
        ),
    ]
