# Generated by Django 2.1.3 on 2018-12-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_max_stored_runs'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='requires_datum_models',
            field=models.BooleanField(default=False),
        ),
    ]
