# Generated by Django 2.1.3 on 2018-12-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_requires_datum_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='attributes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
