# Generated by Django 2.1.3 on 2018-12-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20181208_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='unlisted',
            field=models.BooleanField(default=False),
        ),
    ]
