# Generated by Django 2.1.3 on 2018-12-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_unlisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
