# Generated by Django 2.1.3 on 2018-12-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_run_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='started',
            field=models.DateTimeField(),
        ),
    ]
