# Generated by Django 2.1.3 on 2018-11-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingest_date', models.DateTimeField(auto_now_add=True)),
                ('records_ingested', models.IntegerField()),
                ('last_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField()),
                ('creator_id', models.IntegerField()),
                ('author', models.TextField()),
                ('change', models.IntegerField()),
                ('source', models.URLField()),
                ('score', models.IntegerField()),
                ('fav_count', models.IntegerField()),
                ('md5', models.CharField(max_length=40, unique=True)),
                ('file_size', models.IntegerField()),
                ('file_url', models.URLField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('file_ext', models.CharField(max_length=5)),
                ('preview_url', models.URLField()),
                ('preview_width', models.IntegerField()),
                ('preview_height', models.IntegerField()),
                ('sample_url', models.URLField()),
                ('sample_width', models.IntegerField()),
                ('sample_height', models.IntegerField()),
                ('rating', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=20)),
                ('has_comments', models.BooleanField()),
                ('has_notes', models.BooleanField()),
                ('has_children', models.BooleanField()),
                ('children', models.TextField()),
                ('parent_id', models.IntegerField(null=True)),
                ('artists', models.ManyToManyField(to='posts.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='sources',
            field=models.ManyToManyField(to='posts.Source'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='posts.Tag'),
        ),
    ]
