# Generated by Django 2.1.3 on 2018-11-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(null=True),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['tag'], name='posts_tag_tag_ff7c3b_idx'),
        ),
    ]
