# Generated by Django 2.1.3 on 2018-12-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_tag_tag_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestlog',
            name='new',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingestlog',
            name='updated',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
