# Generated by Django 2.1.3 on 2018-12-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20181205_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestlog',
            name='deletedTags',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ingestlog',
            name='fixed_tags',
            field=models.TextField(blank=True),
        ),
    ]
