# Generated by Django 2.1.3 on 2018-12-05 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20181205_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingestlog',
            old_name='deletedTags',
            new_name='deleted_tags',
        ),
    ]
