# Generated by Django 2.1.3 on 2018-12-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20181205_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingestlog',
            old_name='ingest_date',
            new_name='finished',
        ),
        migrations.AddField(
            model_name='ingestlog',
            name='started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
