# Generated by Django 2.1.3 on 2018-12-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20181213_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_type',
            field=models.IntegerField(choices=[(0, 'general'), (1, 'artist'), (3, 'copyright'), (4, 'character'), (5, 'species'), (10, 'anatomy'), (11, 'act'), (12, 'interest')], default=-1),
        ),
    ]
