# Generated by Django 2.1.3 on 2018-12-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20181216_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_type',
            field=models.IntegerField(choices=[(0, 'general'), (1, 'artist'), (3, 'copyright'), (4, 'character'), (5, 'species'), (10, 'anatomy'), (11, 'gender'), (12, 'act'), (13, 'interest'), (14, 'objects'), (15, 'media')], default=-1),
        ),
    ]
