# Generated by Django 2.1.3 on 2018-12-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20181216_2248'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['tag_type'], name='posts_tag_tag_typ_7f8f33_idx'),
        ),
    ]
